Update Reader.php to include filter by user
DamienHarper/auditor pull request #205
Opened 2024-07-03 06:29 UTC by RomanApunts

2024-07-07 07:52 UTC, DamienHarper approved these changes

2024-07-14 12:30 UTC, DamienHarper requested changes
Thanks @RomanApunts, could you please add some tests so that I can safely merge this PR?

2024-07-15 05:08 UTC, RomanApunts commented
Right now i have no time to do it, maybe in some weeks i can do it…

 

Sorry

 

De: Damien Harper ***@***.*** 
Enviado el: domingo, 14 de julio de 2024 14:31
Para: DamienHarper/auditor ***@***.***>
CC: RomanApunts ***@***.***>; Mention ***@***.***>
Asunto: Re: [DamienHarper/auditor] Update Reader.php to include filter by user (PR #205)

 

@DamienHarper requested changes on this pull request.

Thanks @RomanApunts <https://github.com/RomanApunts> , could you please add some tests so that I can safely merge this PR?

—
Reply to this email directly, view it on GitHub <https://github.com/DamienHarper/auditor/pull/205#pullrequestreview-2176645160> , or unsubscribe <https://github.com/notifications/unsubscribe-auth/AO7YDL7TJENR7GOXO5IB2UTZMJVP7AVCNFSM6AAAAABKI4H6MWVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDCNZWGY2DKMJWGA> .
You are receiving this because you were mentioned.Message ID: ***@***.***>

2024-09-04 08:04 UTC, DamienHarper approved these changes

2024-09-04 08:43 UTC, merged